{
  "base_env": {
    "OHLC_CSV": "data/ohlc.csv",
    "OB_EQ": "10000",
    "OB_RISK": "0.003",
    "OB_MIN_TP": "6",
    "OB_MIN_SL": "6",
    "OB_SPREAD_PIPS": "0.2",
    "OB_FEE_PIPS": "0",
    "OB_MAXDD_STOP": "20"
  },
  "parameters": {
    "OB_KTP": {
      "kind": "range",
      "start": 0.8,
      "stop": 1.6,
      "step": 0.1
    },
    "OB_KSL": {
      "kind": "range",
      "start": 1.0,
      "stop": 2.0,
      "step": 0.2
    },
    "OB_TREND_SMA": {
      "kind": "values",
      "values": [20, 50, 100, 150, 200, 250]
    },
    "OB_RSI": {
      "kind": "pairs",
      "values": [
        [52, 48],
        [55, 45],
        [60, 40]
      ]
    }
  }
}
