name: ci-stability

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - master

jobs:
  stability-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Smoke
        run: |
          python -V
          echo "stability matrix OK"
