name: ci-stability
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  matrix_backtest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pair: [USDJPY, EURJPY, EURUSD]
        period: ["2024-05-01..2024-05-31", "2024-01-01..2024-06-30"]
    env:
      BACKTEST_MODE: ci_offline
      OPENAI_DISABLED: "1"
      NO_MT5: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Prepare config
        run: |
          mkdir -p configs metrics/${{ matrix.pair }}/
          cat <<EOF > configs/matrix_ci.yaml
pair: ${{ matrix.pair }}
period: "${{ matrix.period }}"
output: metrics/${{ matrix.pair }}/metrics.json
EOF
      - name: Run backtest
        run: |
          python run_backtest.py --config configs/matrix_ci.yaml --out metrics/${{ matrix.pair }}/metrics.json
      - name: Upload metrics
        uses: actions/upload-artifact@v4
        with:
          name: metrics-${{ matrix.pair }}-${{ matrix.period }}
          path: metrics/${{ matrix.pair }}/metrics.json
  aggregate_gate:
    runs-on: ubuntu-latest
    needs: matrix_backtest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Download metrics
        uses: actions/download-artifact@v4
        with:
          pattern: metrics-*
          path: metrics
          merge-multiple: true
      - name: Aggregate gate (Phase-B)
        run: |
          python scripts/aggregate_gate.py --root metrics --min_net 0 --min_win 0.45 --max_dd 0.20 --min_trades 30 --min_pass_rate 0.67
