name: ci
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install project deps (if any)
        if: hashFiles("requirements.txt") != ""
        run: pip install -U pip && pip install -r requirements.txt
      - name: Install tools
        run: python -m pip install pytest
      - name: Unit tests (only if tests/ exists)
        if: hashFiles("tests/**") != ""
        run: pytest -q
      - name: Gate check (deterministic)
        run: python scripts/run_gate_check.py
