name: ci

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deterministic gate check
        run: |
          python3 scripts/run_gate_check.py
          echo "✅ YAML encoding OK - workflow valid"
