name: ci(stability)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  stability-check:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('requirements.txt') != '' || hashFiles('tests/**') != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
