name: done-append
on:
  pull_request_target:
    types: [closed]
  workflow_dispatch:
    inputs:
      pr:
        description: "PR number to append from"
        required: true
permissions:
  contents: write
  pull-requests: write
jobs:
  append:
    if: ${{ github.event.pull_request.merged == true || inputs.pr != '' }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number || inputs.pr }}
    steps:
      - uses: actions/checkout@v4

      - id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const pr = Number(process.env.PR_NUMBER);
            const { data: pull } = await github.rest.pulls.get({
              owner: context.repo.owner, repo: context.repo.repo, pull_number: pr
            });
            const body = pull.body || "";
            const m = body.match(/\[DONE ENTRY\]([\s\S]*?)\[\/DONE ENTRY\]/);
            if (!m) core.setFailed("DONE ENTRY が見つかりません");
            const lines = m[1].split(/\r?\n/).map(s=>s.trim()).filter(Boolean);
            const kv = Object.fromEntries(lines.map(l=>{
              const i=l.indexOf(':'); return [l.slice(0,i).trim(), l.slice(i+1).trim()];
            }));
            function esc(s){return (s||"").replace(/\|/g,"／")}
            const mdLine = `- ${esc(kv.date)} JST | ${esc(kv.owner)} | ${esc(kv.artifact)} | ${esc(kv.summary)}`;
            core.setOutput("mdLine", mdLine);

      - name: Ensure docs/DONE.md exists and append entry
        run: |
          mkdir -p docs
          if [ ! -f docs/DONE.md ]; then
            cat > docs/DONE.md <<'EOF'
# DONE (Completed Tasks Log)
- Source of truth: このファイル / 対応PR / CIログ

## 2025-10
EOF
          fi
          echo "${{ steps.extract.outputs.mdLine }}" >> docs/DONE.md

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/done-append-${{ env.PR_NUMBER }}
          title: "Append DONE entry for #${{ env.PR_NUMBER }}"
          commit-message: "chore(done): append DONE for #${{ env.PR_NUMBER }}"
          body: "自動追記: ${{ steps.extract.outputs.mdLine }}"
          signoff: true
